server:
  port: 8080

spring:
  freemarker:
    cache: false
    suffix: .html
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 200MB
      # 上传总的数据大小
      max-request-size: 200MB
  profiles:
    active: dev